---
##################################################################
# 1. Deploy Application Services
##################################################################
- name: Deploy user management service
  kubernetes.core.k8s:
    state: present
    namespace: iot
    definition: "{{ lookup('file', '/home/dfurchert/iotApp/k8s/4-user-management/deployment.yaml') | from_yaml }}"

- name: Deploy auth service
  kubernetes.core.k8s:
    state: present
    namespace: iot
    definition: "{{ lookup('file', '/home/dfurchert/iotApp/k8s/5-auth/deployment.yaml') | from_yaml }}"

- name: Deploy device management service
  kubernetes.core.k8s:
    state: present
    namespace: iot
    definition: "{{ lookup('file', '/home/dfurchert/iotApp/k8s/6-device-management/deployment.yaml') | from_yaml }}"

- name: Deploy data processing service
  kubernetes.core.k8s:
    state: present
    namespace: iot
    definition: "{{ lookup('file', '/home/dfurchert/iotApp/k8s/7-data-processing/deployment.yaml') | from_yaml }}"

##################################################################
# 2. Wait for Application Services to be Ready
##################################################################
- name: Wait for application services to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: iot
  register: app_pods
  until: app_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length > 2
  retries: 30
  delay: 5

##################################################################
# 3. Check Application Readiness via HTTP Health Endpoint
##################################################################
- name: "Wait for application services readiness"
  uri:
    url: "{{ item.url }}"
    method: GET
    return_content: yes
    status_code: 200
  register: app_ready
  until: app_ready.status == 200
  retries: 30
  delay: 5
  loop: "{{ APP_SERVICES }}"
