apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2
          env:
            - name: TZ
              value: "Europe/Zurich"
          ports:
            - containerPort: 1883
            - containerPort: 9001
          volumeMounts:
            - name: mosquitto-storage
              mountPath: /mosquitto/data
            - name: mosquitto-config
              mountPath: /mosquitto/config
            - name: mosquitto-logs
              mountPath: /mosquitto/log
      volumes:
        - name: mosquitto-storage
          persistentVolumeClaim:
            claimName: mosquitto-pvc
        - name: mosquitto-config
          hostPath:
            path: /mosquitto/config
        - name: mosquitto-logs
          hostPath:
            path: /mosquitto/logs
