---
- hosts: k3s_cluster
  become: yes
  gather_facts: yes

  vars:
    kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
    ghcr_username: ""  # Your GitHub username
    ghcr_pat: ""  # Your GitHub Personal Access Token (PAT)
    INFLUXDB_HOST: "http://influxdb.iot.svc.cluster.local:8086"
    MOSQUITTO_HOST: "mosquitto.iot.svc.cluster.local"
    POSTGRES_HOST: "postgres.iot.svc.cluster.local"
    APP_SERVICES:
      - name: auth-service
        url: "http://auth-service.iot.svc.cluster.local:8080/health"
      - name: user-management-service
        url: "http://user-management-service.iot.svc.cluster.local:8080/health"
      - name: device-management-service
        url: "http://device-management-service.iot.svc.cluster.local:8080/health"
      - name: data-processing-service
        url: "http://data-processing-service.iot.svc.cluster.local:8080/health"

  tasks:

    ##################################################################
    # 6. Copy K8s manifests to the Raspberry Pi
    ##################################################################
    - name: Copy all K8s manifests
      copy:
        src: ../k8s/
        dest: /home/dfurchert/iotAppNew/k8s/


    - name: Apply Secrets
      kubernetes.core.k8s:
        state: present
        namespace: iot
        create_namespace: true
        src: "/home/dfurchert/iotAppNew/k8s/secrets.yaml"
        kubeconfig: "{{ kubeconfig_path }}"

    ##################################################################
    # 2. Start Infrastructure (PostgreSQL, InfluxDB, Mosquitto)
    ##################################################################
    - name: Start infrastructure services
      include_role:
        name: startInfra
      vars:
        POSTGRES_HOST: "{{ POSTGRES_HOST }}"
        INFLUXDB_HOST: "{{ INFLUXDB_HOST }}"
        MOSQUITTO_HOST: "{{ MOSQUITTO_HOST }}"

    ##################################################################
    # 3. Set up InfluxDB Buckets
    ##################################################################
    - name: Set up InfluxDB (wait and create buckets)
      include_role:
        name: setUpInflux

    ##################################################################
    # 4. Start Application Services
    ##################################################################
#    - name: Start all backend application services
#      include_role:
#        name: startApplications
#      vars:
#        APP_SERVICES: "{{ APP_SERVICES }}"
#
#    ##################################################################
#    # 5. Start Frontend Services
#    ##################################################################
#    - name: Start all frontend services
#      include_role:
#        name: startFrontend
