---
- hosts: k3s_cluster
  become: yes
  gather_facts: yes

  vars:
    k3s_install_script: "https://get.k3s.io"
    k3s_bin_url: "https://github.com/k3s-io/k3s/releases/download/v1.32.1%2Bk3s1/k3s-arm64"
    k3s_service_file_url: "https://raw.githubusercontent.com/k3s-io/k3s/master/k3s.service"

  tasks:
    ##################################################################
    # 1. Configure Raspberry Pi Environment
    ##################################################################
    - name: Set timezone to Zurich
      timezone:
        name: Europe/Zurich

    - name: Update apt cache
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Upgrade packages
      apt:
        upgrade: dist
        force_apt_get: yes
      register: upgrade_result

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the system if necessary
      reboot:
        reboot_timeout: 300
      when: reboot_required.stat.exists

    - name: Wait for server to come back after reboot
      wait_for_connection:
        delay: 15
        timeout: 300
      when: reboot_required.stat.exists

    - name: Install required dependencies
      apt:
        name:
          - curl
          - socat
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - python3-pip
          #- python3-openshift
          - python3-kubernetes
          - rfkill
        state: present

    ##################################################################
    # 2. Turn off Wi-Fi
    ##################################################################
    - name: Disable Wi-Fi
      command: rfkill block wifi